kimik2.5-fp4-mi355x-vllm-disagg-mpnd-normal:
  image: vllm/vllm-openai-rocm:nightly-09663abde0f50944a8d5ea30120666024b503faa
  model: amd/Kimi-K2.5-MXFP4
  model-prefix: kimik2.5
  runner: mi355x-disagg
  precision: fp4
  framework: vllm-disagg
  multinode: true
  disagg: true
  scenarios:
    fixed-seq-len:
    - isl: 1024
      osl: 1024
      search-space:
      - spec-decoding: "none"
        conc-list: [ 512, 1024 ]
        prefill:
          num-worker: 1
          tp: 4
          ep: 4
          dp-attn: false
          additional-settings:
          - "PREFILL_NODES=1"
          - "VLLM_MORIIO_CONNECTOR_READ_MODE=1"
        decode:
          num-worker: 1
          tp: 8
          ep: 8
          dp-attn: false
          additional-settings:
          - "DECODE_NODES=1"
          - "VLLM_MORIIO_CONNECTOR_READ_MODE=1"
      - spec-decoding: "none"
        conc-list: [ 1024, 2048 ]
        prefill:
          num-worker: 1
          tp: 4
          ep: 4
          dp-attn: false
          additional-settings:
          - "PREFILL_NODES=1"
          - "VLLM_MORIIO_CONNECTOR_READ_MODE=1"
        decode:
          num-worker: 2
          tp: 8
          ep: 8
          dp-attn: false
          additional-settings:
          - "DECODE_NODES=2"
          - "VLLM_MORIIO_CONNECTOR_READ_MODE=1"

    - isl: 8192
      osl: 1024
      search-space:
      - spec-decoding: "none"
        conc-list: [ 512, 1024 ]
        prefill:
          num-worker: 2
          tp: 4
          ep: 4
          dp-attn: false
          additional-settings:
          - "PREFILL_NODES=2"
          - "VLLM_MORIIO_CONNECTOR_READ_MODE=1"
        decode:
          num-worker: 1
          tp: 8
          ep: 8
          dp-attn: false
          additional-settings:
          - "DECODE_NODES=1"
          - "VLLM_MORIIO_CONNECTOR_READ_MODE=1"
      - spec-decoding: "none"
        conc-list: [ 1024 ]
        prefill:
          num-worker: 4
          tp: 4
          ep: 4
          dp-attn: false
          additional-settings:
          - "PREFILL_NODES=4"
          - "VLLM_MORIIO_CONNECTOR_READ_MODE=1"
        decode:
          num-worker: 1
          tp: 8
          ep: 8
          dp-attn: false
          additional-settings:
          - "DECODE_NODES=1"
          - "VLLM_MORIIO_CONNECTOR_READ_MODE=1"
